fix

diff --git a/.github/workflows/hello.yml b/.github/workflows/hello.yml
--- a/.github/workflows/hello.yml
+++ b/.github/workflows/hello.yml
@@ -19,38 +19,23 @@ jobs:
       - name: Setup Node
         uses: actions/setup-node@v3
         with:
-          node-version: '14'
+          node-version: '20'
 
       - name: Install Dependencies
         run: npm ci
 
-      - name: Run Tests and Capture Output
+    #   - name: Run Tests and Capture Output
+    #     run: npm test 
+
+
+
+      - name: Run tests
         run: npm test 
 
-      - name: Comment PR with Test Results
-        if: always()
-        env:
-          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
-        run: |
-          comment_body=$(cat reports/test-results.xml)
-          if [ -z "$comment_body" ]; then
-            comment_body="No test results found."
-          fi
-          curl -X POST \
-            -H "Authorization: token $GITHUB_TOKEN" \
-            -H "Accept: application/vnd.github.v3+json" \
-            -d "{\"body\":\"Test Results:\\n\`\`\`\\n${comment_body}\\n\`\`\`\"}" \
-            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
-
-
-
-        # - name: Run tests
-        #   run: npm test 
-
-        # - name: Test Report
-        #   uses: dorny/test-reporter@v1
-        #   if: success() || failure()    # run this step even if previous step failed
-        #   with:
-        #     name: JEST Tests            # Name of the check run which will be created
-        #     path: reports/jest-*.xml    # Path to test results
-        #     reporter: jest-junit
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: JEST Tests            # Name of the check run which will be created
+          path: reports/jest-*.xml    # Path to test results
+          reporter: jest-junit
